apiVersion: v1
kind: PersistentVolume
metadata:
  name: fresco-pv
  labels:
    type: local
spec:
  capacity:
    storage: 100MB
  accessModes:
    - ReadWriteOnce                              
  storageClassName: manual
  hostPath:
    path: "/tmp/fresco"
