apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fresco-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 50MB
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
